### ISSUE TITLE
Cannot require scoped npm package in function

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/api-bugs#225] opened 2017-08-08 23:11 UTC
**What is the current behavior?**
Requiring a scoped package returns a server error.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**
```es6
import * as googleMaps from '@google/maps'
```
Error:
```js
"Function returned invalid status code:: 400. Raw body: {\n  \"code\": 400,\n  \"message\": \"Compilation failed: Cannot find module '@google/maps'\",\n  \"error\": \"Cannot find module '@google/maps'\"
```

**What is the expected behavior?**
Able to require scoped packages without error.

**Comment by marktani** [comment] 2017-08-09 08:40
Looks like a duplicate of #170 to me, or am I wrong?

**Comment by kbrandwijk** [comment] 2017-08-09 08:59
No it's not. Normal packages where you want to require an export from a subfolder are dealt with in #170. The 'import ... from ...' syntax works there, so I don't believe that's still an issue actually. 

This is regarding _scoped packages_, so packages that start with '@something/...'. They do *not* work, even with the 'import' syntax.

**Comment by marktani** [comment] 2017-08-09 10:02
Ah ok, thanks for the clarification! 🙂

**Closed** 2017-09-08 09:52 UTC
Labels: kind/bug
