### ISSUE TITLE
updatedFields_contains not working in subscriptions API

### ISSUE THREAD

**Issue by lastmjs** [graphcool/api-bugs#98] opened 2017-06-08 23:00 UTC
I'm trying to listen to created or updated user nodes, and if updated just one field in particular

Here is my subscription:
```
subscription {
  User(filter: {
    OR: [
      {
        mutation_in: [CREATED]
      },
      {
           mutation_in: [UPDATED]
            updatedFields_contains: "ltiJWT" 
      }
    ]
  }) {
    node {
      id
      ltiJWT
    }
  }
}
```

But I get this error:

```
"Query does not pass validation. Violations:

Argument 'filter' expected type 'UserSubscriptionFilter' but got: {OR: [{boolean: true}, {boolean: false, updatedFields_contains: "ltiJWT"}]}. Reason: [in field 'OR'] [at index #1] Unknown field 'updatedFields_contains' is not defined in the input type 'UserSubscriptionFilter'. (line 9, column 7):
            updatedFields_contains: "ltiJWT" 
      ^ (line 9, column 7):
            updatedFields_contains: "ltiJWT" 
      ^ (line 2, column 16):
  User(filter: {
               ^
 (line 9, column 7):
            updatedFields_contains: "ltiJWT" 
      ^"
```

@marktani said: 

> hey, this looks to be a problem with the Subscriptions API schema that we're generating. `updatedFields_contains` doesn't seem to be available in the filter even though it should.

**Comment by marktani** [comment] 2017-06-16 16:30
Thanks for bringing this up! The problem is now fixed. 🙂

**Closed by marktani** 2017-06-16 16:30 UTC
Labels: area/subscriptions

**Comment by mcmar** [comment] 2018-06-02 23:28
@marktani Things I tried:
```
subscription {
  User(
    filter: {
    	OR: [{
        mutation_in: [CREATED]
      }, {
        mutation_in: [UPDATED],
        OR: [{
          updatedFields_contains: "latitude"
        }, {
          updatedFields_contains: "longitude"
        }]
      }]
    }
  ) {
    node {
      id
      latitude
      longitude
      city {
        id
      }
    }
  }
}
```
This one works in graphcool playground, but fails in production.
Also tried this one:
```
subscription {
  User(
    filter: {
      OR: [{
        mutation_in: [CREATED]
      }, {
        mutation_in: [UPDATED]
        updatedFields_contains_some: ["latitude", "longitude"]
      }]
    }
  ) {
    node {
      id
      latitude
      longitude
      city {
        id
      }
    }
  }
}
```
That one has the same thing. It works in Graphcool Playground, but fails in production.
