### ISSUE TITLE
Nested mutations can break required relations

### ISSUE THREAD

**Issue by sorenbs** [graphcool/api-bugs#120] opened 2017-06-16 15:13 UTC
```graphql
createPost(
    text: "text",
    metaInformationId: "not a real id"
  ) {
    id
  }
```

See https://github.com/graphcool/api-bugs/issues/12

**Comment by marktani** [comment] 2017-06-29 15:42
Duplicate of #12.

**Closed** 2017-06-30 15:55 UTC
Labels: area/api
