### ISSUE TITLE
Simple API returns status code 200 even if permission denied

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/api-bugs#125] opened 2017-06-18 15:15 UTC
**What is the current behavior?**
Posting a mutation to the simple API always returns '200', even if permission is denied.

**What is the expected behavior?**
It would be a lot easier to handle different situations in RP, SSS and WT if the API would return a 403.

**Comment by marktani** [comment] 2017-06-18 15:37
This is not a bug, but intended behaviour and part of the GraphQL paradigm.

GraphQL responses contain a `data` and an `errors` property. This is useful when an error only affects parts of the response.

* Our documentation describes the way [insufficient permission errors and query responses](https://www.graph.cool/docs/faq/graphcool-insufficient-permissions-query-response-noohie9hai/) interact.

* For functions, you can actually return an object that contains the `error` property (either a String or a JSON object). It will be included in the response to the GraphQL client that initiated the mutation: https://www.graph.cool/docs/reference/functions/error-handling-quawa7aed0/

**Comment by kbrandwijk** [comment] 2017-06-18 16:09
I am not talking about a query, but about a mutation. For mutations, permissions cannot affect part of the mutation.

**Comment by marktani** [comment] 2017-06-18 17:01
It's consistent to return permission errors in the same way for queries and mutations. Note that a mutation also returns a response that follows the behaviour as mentioned above when an insufficient permission errors occurs.

Have you looked into checking if the GraphQL response contains the `errors` object and if so, parsing that for the error code?

**Comment by kbrandwijk** [comment] 2017-06-18 17:38
Yes, the behavior is more or less consistent. You always get a `data` object and an `error` object. There is some inconsistency for when the query name is part of the `data` object or not though. Sometimes `data` is null, sometimes `data/someQueryOrMutation` is null. I haven't figured out the exact cases for both though.

And yes, if you know the error codes, you can also do error handling based on that. Traditionally though, the HTTP status code is the first thing I check. There are quite a few that apply, including, but not limited to:
201 after a succesful create mutation, 
102 on big nested mutations, 
403 on permission errors, 
418 if you happen to query on a Teapot Type etc.

However, with the availability of the current error codes, let's move to feature-request.

**Comment by wallslide** [comment] 2017-06-21 10:31
Since you can put multiple queries/mutations into a single call, it makes sense that permission denials happen at the current query/mutation/data level rather than the http-call level.

**Comment by marktani** [comment] 2017-06-22 20:51
Indeed, I feel like the [feature requests](https://github.com/graphcool/feature-requests) is a better place to discuss this. Feel free to continue the discussion there.

**Closed by marktani** 2017-06-22 20:51 UTC
Labels: discussion
