### ISSUE TITLE
User Create permissions not respected with authProvider auth0 and createUser

### ISSUE THREAD

**Issue by cj** [graphcool/api-bugs#182] opened 2017-07-13 22:13 UTC
**What is the current behavior?**

User Create Permissions are not respected for authProvider `auth0` when using `createUser`.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

Just create a brand new project, with this scheme https://gist.github.com/043756a5cbc1dac462aa60d340c54d80 add and config the auth0 integration, make sure to use google-oauth.  In graph.cool change the User Create permission to authenticated.

**If applicable, share the query, mutation or subscription for reproduction**

Now using come code similar to https://gist.github.com/cj/38482442c928af7635d0e71a8769f4fc login to auth0 and then call `createUser`.

**What is the expected behavior?**

It should not create a user and return permission denied.  Instead, the user gets created.

**Comment by marktani** [comment] 2017-07-21 19:22
I'm closing this because it's intended behaviour. Please read [this thread](https://github.com/graphcool/api-bugs/issues/150) for more information and reach out to me in Slack if needed 🙂

**Closed by marktani** 2017-07-21 19:22 UTC
